### ISSUE TITLE
Notificações

### ISSUE THREAD

**Issue by johnidm** [johnidm/owl-links#2]
Ao lançar novos registros na sugestão de links, newslatter e contato enviar um e-mail para notificação.

**Comment by Alexandre-Busarello** [comment]
Oi @johnidm,

Estava dando uma olhada nesta issue, ainda não conseguir validar. Somente vou conseguir em casa, mas em resumos sua ideia é apenas gerar uma e-mail de notificação (simples) com as informações quando alguém sugerir um link, cadastrar um contato ou assinar a newslatter, certo?

Abraços,
Alexandre Busarello.

**Comment by johnidm** [comment]
Tudo bom @Alexandre-Busarello? 

Obrigado pelo interesse em ajudar.

A ideia é essa que você mencionou.

Eu pensei em algo assim:
- No arquivo application.conf (https://github.com/johnidm/owl-links/tree/master/conf) incluir uma chave chamada `emails.notifications` ou algo parecido com isso. Nessa chave teria uma lista de emails separados por `;`. Ex: notifications_new_records=fulano@fulano.com;ciclano@ciclano.com
- Ler essa configuração com a função `Play.application().configuration().getString( "emails.notifications" ) )` e transformar em uma lista de emails.
- Usar a biblioteca `org.apache.commons.mail` para enviar um e-mail a cada nova registro incluído nas tabelas em questão. Ex de envio de e-mail: `https://github.com/johnidm/owl-links/blob/master/app/utils/MailNotifycation.java`.

Nos controladores de cada tabela tem o método que salva o registro no DB, a chamada da função pode ser incluída depois de salvar o registro.

Qualquer dúvida me avise.

**Comment by Alexandre-Busarello** [comment]
@johnidm 

A etapa de alterar e disparar os e-mails de notificação eu já fiz, mas eu coloquei um e-mail fixo para testes pois não tinha tido nenhuma ideia de onde buscar os e-mails que serão notificados. Vou alterar para pegar das configurações conforme sua sugestão.

Outro detalhe é que eu ainda não consegui validar os envios dos e-mails pois aqui onde trabalho o gmail é bloqueado e acredito este ser o motivo de não conseguir enviar os e-mails.

No mais é isto, vou ver se adianto este assunto em casa.

Obrigado.

**Comment by johnidm** [comment]
Ok, Alexandre me passa o teu e-mail que eu mando a senha do e-mail do Owl para você testar.

Abraço.

**Comment by Alexandre-Busarello** [comment]
@johnidm 

busamar@gmail.com

**Comment by Alexandre-Busarello** [comment]
Ola @johnidm , não precisa mandar o e-mail pois este já tinha a senha configurado no próprio fonte.

Consegui fazer o teste em casa e os e-mails foram enviados com sucesso. Vou fazer uns ajustes no corpo do e-mail e implementar as notificações conforme sua sugestão e enviar logo para você dar uma olhada.

Um detalhe que notei é que o envia do e-mail deixou o cadastro de link, contato e newslatter um pouco mais lento. Uma solução seria apenas registrar uma intenção de envio (em uma tabela) e o e-mail ser montado e enviado posteriormente pelo servidor.

Atenciosamente,
Alexandre Busarello.

**Comment by johnidm** [comment]
Legal @Alexandre-Busarello obrigado

Acho interessante a sua sugestão de usar uma tabela, podemo fazer isso, você quer que eu crie outra issue para isso, ou você quer desenvolver?

A minha sugestão nesse caso da tabela:
- Criar um `model` com a estrutura da tabela de notificações, e aplicar a evolução do DB pelo Play
- Alimentar a tabela quando novos registros foram incluídos.
- Para fazer o processamento em background, podemos usar o mesmo código do envio de e-mail da newlatter, que está na classe global.

Abraço.

**Comment by Alexandre-Busarello** [comment]
@johnidm , vamos fazer assim, eu vou concluir do jeito que te falei agora (sem a tabela e processamento em background). Após concluído isto eu gero uma issue para esta segunda parte. Pode ser?

Eu gostaria de desenvolver mas está meio corrido então deixo registrado e caso ninguém fazer eu faço posteriormente.

**Comment by johnidm** [comment]
@Alexandre-Busarello  sim, claro, pode ser como você sugeriu.

Abraço

**Comment by Alexandre-Busarello** [comment]
Oi @johnidm , criei uma pull referente as alterações para atender esta issue.
Também registrei duas novas issues visando melhorar este processo. São as issues #15 e #16 .

**Comment by johnidm** [comment]
@Alexandre-Busarello versão 0.0.3 gerada, já fiz o deploy no Heroku e as suas alterações já estão em produção.

Obrigado pela ajuda.
