### ISSUE TITLE
Menu não aparece na versão responsiva

### ISSUE THREAD

**Issue by johnidm** [johnidm/owl-links#3]
O menu não esta aparecendo quando diminui a resolução para versões mobile

**Comment by joelvisroman** [comment]
Percebi que o menu não aparece por ter um possível conflito entre o espaço onde esta a coruja(topo) e o espaço destinado para o menu, por algum motivo quem vence é sempre a coruja!

![992](https://cloud.githubusercontent.com/assets/7695889/6732350/fb8a1806-ce29-11e4-81c9-373f2a7c6d4f.png)
![993](https://cloud.githubusercontent.com/assets/7695889/6732349/fb87d064-ce29-11e4-9d38-4357d9cbf176.png)

**Comment by johnidm** [comment]
Algumas classes CSS estavam sendo utilizadas de forma incorreta.

@joelvisroman obrigado.
