### ISSUE TITLE
Validação no campo do link

### ISSUE THREAD

**Issue by AlexandreProenca** [johnidm/owl-links#36]
O campo não esta validando se o conteudo esta vazio, seria interessante só habilitar o botão de enviar quando o campo receber uma url valida.

**Comment by johnidm** [comment]
Outro problema esta relacionado a links muito longos. Esta dando erro ao cadatra-los

**Comment by johnidm** [comment]
versão 0.0.8

**Comment by johnidm** [comment]
versão 0.0.8
