### ISSUE TITLE
card page-wrapper

### ISSUE THREAD

**Issue by joelvisroman** [johnidm/owl-links#8]
Os links não são formatados de forma correta para exibição da página.
Ex:  Ao clicar em ACESSE o que traz é http//fritzing.org, esse link é inassinável.

**Comment by johnidm** [comment]
Ola @joelvisroman obrigado pelo seu feedback, vou verificar o motivo do problema. 

Grande abraço.

**Comment by johnidm** [comment]
Ola @joelvisroman obrigado pela informação.

Vou analisar o pull request #9 que você me enviou.

Abraço.
